---
id: Feed
name: Feed
full: Feed client library
description: A library for working with feed formats such as RSS and Atom.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Feed
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha2
  api: 1.1.0
state:
  release: stable
  api: stable
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
      horde/http: ^3
      horde/xml_element: ^3
    ext:
      dom: '*'
  optional:
    composer:
      horde/test: ^3
